---
# defaults file for cloud-student
common_node_config_options:
  - dest: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: Port {{ ssh_port | default('22') }}
    validate: sshd -t -f %s

  - dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
    validate: sshd -t -f %s

  - dest: /etc/ssh/sshd_config
    regexp: '^#?UseDNS'
    line: 'UseDNS no'
    validate: sshd -t -f %s

  - dest: /etc/sudoers
    regexp: '^{{ student_name }}'
    line: '{{ student_name }} ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

  - dest: /etc/sudoers
    regexp: '^Defaults.*requiretty'
    line: 'Defaults    !requiretty'
    validate: visudo -cf %s

firewall_rules:
  - service: http
  - service: https
  - service: ssh
  - port: 5432
    protocol: udp
  - port: 5672
    protocol: udp
  - port: 5432
    protocol: tcp
  - port: 5672
    protocol: tcp

firewalld_service: firewalld
