---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Generate SSH keys
      shell: ssh-keygen -b 2048 -t rsa -f "{{ workshop_name }}_key" -I "{{ workshop_name }}" -q -N ""
      args:
        creates: "./{{ workshop_name }}_key"

    - include_tasks: build-student.yml
      with_sequence: count="{{ num_students }}"
      loop_control:
        loop_var: student_number

    - debug: var=cloud_instance_dict
