---
- hosts: routers
  connection: local
  gather_facts: no
  vars:
    backup_root: ./backup

  tasks:
    - set_fact:
        backup_file: "{{ backup_root }}/{{ inventory_hostname }}"

    - name: Backup the config
      ios_config:
        backup: yes
      register: config_output

    - name: Create link to the most recent config
      file:
        src: "{{ config_output.backup_path }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}"
        state: link